apiVersion: v1
kind: Service
metadata:
  name: evalsecurrity-service
spec:
  type: NodePort
  selector:
    app: evalsecurrity
  ports:
    - name: http
      port: 8087
      targetPort: 8088
      nodePort: 30005


